remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Capgemini few-shot segmentation
description: An investigation into different network architectures within few-shot segementation 
